<a href="https://colab.research.google.com/github/Suyash-28-commits/Titanic-Survival-Prediction/blob/main/Prediction_without_using_pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pickle
import numpy as np

In [ ]:
ohe_sex= pickle.load(open('/content/drive/MyDrive/models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('/content/drive/MyDrive/models/ohe_embarked.pkl','rb'))
dr = pickle.load(open('/content/drive/MyDrive/models/dr.pkl','rb'))

In [ ]:
#Assumed input
#Pclass/gender/Age/SibSp/Parch/Fare/Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [ ]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
test_input_sex

array([[0., 1.]])

In [ ]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [ ]:
test_input_embarked

array([[0., 0., 1.]])

In [ ]:
test_input_age = test_input[:,2].reshape(1,1)

In [ ]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [ ]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [ ]:
test_input_transformed.shape

(1, 10)

In [ ]:
dr.predict(test_input_transformed)

array([1])

In [2]:
import json

# Path to the notebook you want to fix
file_path = "/content/drive/MyDrive/Colab Notebooks/Prediction without using pipelines.ipynb"

# Load the notebook as a JSON object
with open(file_path, "r", encoding="utf-8") as f:
    notebook_data = json.load(f)

# Remove broken widgets from metadata if they exist
if "widgets" in notebook_data.get("metadata", {}):
    print("Fixing metadata.widgets...")
    del notebook_data["metadata"]["widgets"]

# Save the cleaned notebook
with open(file_path, "w", encoding="utf-8") as f:
    json.dump(notebook_data, f, indent=1)

print("Notebook fixed and saved successfully.")


Notebook fixed and saved successfully.
